
name: active-learning
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - pip=22.2.2
  - pip:
    - numpy==1.26.2
    - torchvision==0.16.1
    - torch==2.1.1
    - scikit-learn==1..2
    - tqdm==4.66.1
    - ipdb==0.13.13
    - wandb==0.16.1
